/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSplatRouteImport } from './routes/auth/$'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardTripsIndexRouteImport } from './routes/_authenticated/dashboard/trips/index'
import { Route as AuthenticatedDashboardTripsNewRouteImport } from './routes/_authenticated/dashboard/trips/new'
import { Route as AuthenticatedDashboardTripsTripIdIndexRouteImport } from './routes/_authenticated/dashboard/trips/$tripId/index'
import { Route as AuthenticatedDashboardTripsTripIdCalendarRouteImport } from './routes/_authenticated/dashboard/trips/$tripId/calendar'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/auth/$',
  path: '/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardTripsIndexRoute =
  AuthenticatedDashboardTripsIndexRouteImport.update({
    id: '/dashboard/trips/',
    path: '/dashboard/trips/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardTripsNewRoute =
  AuthenticatedDashboardTripsNewRouteImport.update({
    id: '/dashboard/trips/new',
    path: '/dashboard/trips/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardTripsTripIdIndexRoute =
  AuthenticatedDashboardTripsTripIdIndexRouteImport.update({
    id: '/dashboard/trips/$tripId/',
    path: '/dashboard/trips/$tripId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardTripsTripIdCalendarRoute =
  AuthenticatedDashboardTripsTripIdCalendarRouteImport.update({
    id: '/dashboard/trips/$tripId/calendar',
    path: '/dashboard/trips/$tripId/calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/auth/$': typeof AuthSplatRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/trips/new': typeof AuthenticatedDashboardTripsNewRoute
  '/dashboard/trips': typeof AuthenticatedDashboardTripsIndexRoute
  '/dashboard/trips/$tripId/calendar': typeof AuthenticatedDashboardTripsTripIdCalendarRoute
  '/dashboard/trips/$tripId': typeof AuthenticatedDashboardTripsTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/auth/$': typeof AuthSplatRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/trips/new': typeof AuthenticatedDashboardTripsNewRoute
  '/dashboard/trips': typeof AuthenticatedDashboardTripsIndexRoute
  '/dashboard/trips/$tripId/calendar': typeof AuthenticatedDashboardTripsTripIdCalendarRoute
  '/dashboard/trips/$tripId': typeof AuthenticatedDashboardTripsTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/auth/$': typeof AuthSplatRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/trips/new': typeof AuthenticatedDashboardTripsNewRoute
  '/_authenticated/dashboard/trips/': typeof AuthenticatedDashboardTripsIndexRoute
  '/_authenticated/dashboard/trips/$tripId/calendar': typeof AuthenticatedDashboardTripsTripIdCalendarRoute
  '/_authenticated/dashboard/trips/$tripId/': typeof AuthenticatedDashboardTripsTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/auth/$'
    | '/dashboard'
    | '/dashboard/trips/new'
    | '/dashboard/trips'
    | '/dashboard/trips/$tripId/calendar'
    | '/dashboard/trips/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/auth/$'
    | '/dashboard'
    | '/dashboard/trips/new'
    | '/dashboard/trips'
    | '/dashboard/trips/$tripId/calendar'
    | '/dashboard/trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/auth/$'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/trips/new'
    | '/_authenticated/dashboard/trips/'
    | '/_authenticated/dashboard/trips/$tripId/calendar'
    | '/_authenticated/dashboard/trips/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthSplatRoute: typeof AuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$': {
      id: '/auth/$'
      path: '/auth/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/trips/': {
      id: '/_authenticated/dashboard/trips/'
      path: '/dashboard/trips'
      fullPath: '/dashboard/trips'
      preLoaderRoute: typeof AuthenticatedDashboardTripsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/trips/new': {
      id: '/_authenticated/dashboard/trips/new'
      path: '/dashboard/trips/new'
      fullPath: '/dashboard/trips/new'
      preLoaderRoute: typeof AuthenticatedDashboardTripsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/trips/$tripId/': {
      id: '/_authenticated/dashboard/trips/$tripId/'
      path: '/dashboard/trips/$tripId'
      fullPath: '/dashboard/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedDashboardTripsTripIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/trips/$tripId/calendar': {
      id: '/_authenticated/dashboard/trips/$tripId/calendar'
      path: '/dashboard/trips/$tripId/calendar'
      fullPath: '/dashboard/trips/$tripId/calendar'
      preLoaderRoute: typeof AuthenticatedDashboardTripsTripIdCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardTripsNewRoute: typeof AuthenticatedDashboardTripsNewRoute
  AuthenticatedDashboardTripsIndexRoute: typeof AuthenticatedDashboardTripsIndexRoute
  AuthenticatedDashboardTripsTripIdCalendarRoute: typeof AuthenticatedDashboardTripsTripIdCalendarRoute
  AuthenticatedDashboardTripsTripIdIndexRoute: typeof AuthenticatedDashboardTripsTripIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardTripsNewRoute: AuthenticatedDashboardTripsNewRoute,
  AuthenticatedDashboardTripsIndexRoute: AuthenticatedDashboardTripsIndexRoute,
  AuthenticatedDashboardTripsTripIdCalendarRoute:
    AuthenticatedDashboardTripsTripIdCalendarRoute,
  AuthenticatedDashboardTripsTripIdIndexRoute:
    AuthenticatedDashboardTripsTripIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthSplatRoute: AuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
