/**
 * Portuguese (pt-BR) localization for Neon Auth UI
 * Based on @daveyplate/better-auth-ui authLocalization structure
 */
export const authLocalizationPtBR = {
  // Error messages
  INVALID_USERNAME_OR_PASSWORD: "Usuário ou senha inválidos",
  EMAIL_NOT_VERIFIED: "Email não verificado",
  UNEXPECTED_ERROR: "Erro inesperado",
  USERNAME_IS_ALREADY_TAKEN: "Nome de usuário já está em uso",
  USERNAME_TOO_SHORT: "Nome de usuário muito curto",
  USERNAME_TOO_LONG: "Nome de usuário muito longo",
  INVALID_USERNAME: "Nome de usuário inválido",
  INVALID_EMAIL: "Email inválido",
  USER_NOT_FOUND: "Usuário não encontrado",
  TOO_MANY_ATTEMPTS: "Muitas tentativas. Tente novamente mais tarde",
  USER_ALREADY_EXISTS: "Usuário já existe",
  INVALID_PASSWORD: "Senha inválida",
  INVALID_EMAIL_OR_PASSWORD: "Email ou senha inválidos",
  PASSWORD_TOO_SHORT: "Senha muito curta",
  PASSWORD_TOO_LONG: "Senha muito longa",
  SESSION_EXPIRED: "Sessão expirada",

  // UI Labels
  APP: "Luis Travel",
  ACCOUNT: "Conta",
  ACCOUNTS: "Contas",
  ACCOUNTS_DESCRIPTION: "Gerencie suas contas conectadas.",
  ADD_ACCOUNT: "Adicionar Conta",
  ALREADY_HAVE_AN_ACCOUNT: "Já tem uma conta?",
  AVATAR: "Avatar",
  AVATAR_DESCRIPTION: "Clique no avatar para enviar uma imagem personalizada.",
  CANCEL: "Cancelar",
  CHANGE_PASSWORD: "Alterar Senha",
  CHANGE_PASSWORD_DESCRIPTION: "Digite sua senha atual e uma nova senha.",
  CHANGE_PASSWORD_INSTRUCTIONS: "Use pelo menos 8 caracteres.",
  CHANGE_PASSWORD_SUCCESS: "Sua senha foi alterada.",
  CONFIRM_PASSWORD: "Confirmar Senha",
  CONFIRM_PASSWORD_PLACEHOLDER: "Confirmar Senha",
  CONFIRM_PASSWORD_REQUIRED: "Confirmação de senha é obrigatória",
  CONTINUE: "Continuar",
  CURRENT_PASSWORD: "Senha Atual",
  CURRENT_PASSWORD_PLACEHOLDER: "Senha Atual",
  DELETE: "Excluir",
  DELETE_AVATAR: "Excluir Avatar",
  DELETE_ACCOUNT: "Excluir Conta",
  DELETE_ACCOUNT_DESCRIPTION:
    "Remova permanentemente sua conta e todo o seu conteúdo. Esta ação não pode ser desfeita.",
  DONT_HAVE_AN_ACCOUNT: "Não tem uma conta?",
  DONE: "Concluído",
  EMAIL: "Email",
  EMAIL_DESCRIPTION: "Digite o endereço de email que deseja usar para login.",
  EMAIL_INSTRUCTIONS: "Por favor, digite um email válido.",
  EMAIL_PLACEHOLDER: "seu@email.com",
  EMAIL_REQUIRED: "Email é obrigatório",
  EMAIL_VERIFICATION: "Verifique seu email para o link de verificação.",
  FORGOT_PASSWORD: "Esqueci a Senha",
  FORGOT_PASSWORD_ACTION: "Enviar link de redefinição",
  FORGOT_PASSWORD_DESCRIPTION: "Digite seu email para redefinir sua senha",
  FORGOT_PASSWORD_EMAIL: "Verifique seu email para o link de redefinição.",
  FORGOT_PASSWORD_LINK: "Esqueceu sua senha?",
  MAGIC_LINK: "Link Mágico",
  MAGIC_LINK_ACTION: "Enviar link mágico",
  MAGIC_LINK_DESCRIPTION: "Digite seu email para receber um link mágico",
  MAGIC_LINK_EMAIL: "Verifique seu email para o link mágico",
  NAME: "Nome",
  NAME_DESCRIPTION: "Por favor, digite seu nome completo.",
  NAME_INSTRUCTIONS: "Use no máximo 32 caracteres.",
  NAME_PLACEHOLDER: "Seu Nome",
  NEW_PASSWORD: "Nova Senha",
  NEW_PASSWORD_PLACEHOLDER: "Nova Senha",
  OR: "ou",
  OR_CONTINUE_WITH: "ou continue com",
  PASSWORD: "Senha",
  PASSWORD_DESCRIPTION: "Digite uma senha segura.",
  PASSWORD_INSTRUCTIONS: "Use pelo menos 8 caracteres.",
  PASSWORD_PLACEHOLDER: "Senha",
  PASSWORD_REQUIRED: "Senha é obrigatória",
  PASSWORDS_DONT_MATCH: "As senhas não coincidem",
  REMEMBER_ME: "Lembrar de mim",
  RESET_PASSWORD: "Redefinir Senha",
  RESET_PASSWORD_DESCRIPTION: "Digite sua nova senha abaixo.",
  RESET_PASSWORD_SUCCESS: "Sua senha foi redefinida.",
  SAVE: "Salvar",
  SAVE_CHANGES: "Salvar Alterações",
  SETTINGS: "Configurações",
  SIGN_IN: "Entrar",
  SIGN_IN_DESCRIPTION: "Digite seu email abaixo para acessar sua conta",
  SIGN_IN_ACTION: "Entrar",
  SIGN_IN_LINK: "Entrar",
  SIGN_IN_WITH: "Entrar com",
  SIGN_OUT: "Sair",
  SIGN_OUT_DESCRIPTION: "Encerrar sua sessão atual.",
  SIGN_OUT_SUCCESS: "Você saiu com sucesso.",
  SIGN_UP: "Criar Conta",
  SIGN_UP_DESCRIPTION: "Crie uma conta para começar",
  SIGN_UP_ACTION: "Criar Conta",
  SIGN_UP_LINK: "Criar Conta",
  SUBMIT: "Enviar",
  SUCCESS: "Sucesso",
  UPDATE: "Atualizar",
  USERNAME: "Nome de Usuário",
  USERNAME_PLACEHOLDER: "Nome de Usuário",

  // Social providers
  CONTINUE_WITH_GOOGLE: "Continuar com Google",
  CONTINUE_WITH_GITHUB: "Continuar com GitHub",
  CONTINUE_WITH_APPLE: "Continuar com Apple",
  CONTINUE_WITH_FACEBOOK: "Continuar com Facebook",
  CONTINUE_WITH_MICROSOFT: "Continuar com Microsoft",

  // Session
  CURRENT_SESSION: "Sessão Atual",
  SESSIONS: "Sessões",
  SESSIONS_DESCRIPTION: "Gerencie suas sessões ativas.",
  REVOKE_SESSION: "Encerrar Sessão",
  REVOKE_ALL_SESSIONS: "Encerrar Todas as Sessões",

  // Two-factor
  TWO_FACTOR: "Autenticação em Duas Etapas",
  TWO_FACTOR_DESCRIPTION: "Adicione uma camada extra de segurança à sua conta.",
  ENABLE_TWO_FACTOR: "Ativar Autenticação em Duas Etapas",
  DISABLE_TWO_FACTOR: "Desativar Autenticação em Duas Etapas",
  BACKUP_CODES: "Códigos de Backup",
  BACKUP_CODES_DESCRIPTION:
    "Salve estes códigos em um lugar seguro. Você pode usá-los para acessar sua conta se perder seu método de autenticação.",

  // Passkey
  ADD_PASSKEY: "Adicionar Passkey",
  PASSKEY: "Passkey",
  PASSKEYS: "Passkeys",
  PASSKEYS_DESCRIPTION: "Gerencie suas passkeys para login sem senha.",

  // Linked accounts
  LINKED_ACCOUNTS: "Contas Vinculadas",
  LINKED_ACCOUNTS_DESCRIPTION: "Gerencie as contas vinculadas ao seu perfil.",
  LINK_ACCOUNT: "Vincular Conta",
  UNLINK_ACCOUNT: "Desvincular Conta",

  // Validation
  IS_INVALID: "é inválido",
  IS_REQUIRED: "é obrigatório",
  IS_THE_SAME: "é o mesmo",
} as const
